# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('book_code', models.CharField(blank=True, max_length=4, unique=True)),
                ('author', models.CharField(blank=True, max_length=40, null=True)),
                ('publisher', models.CharField(blank=True, max_length=40, null=True)),
                ('category', models.CharField(max_length=40, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('issued_date', models.DateTimeField(null=True)),
                ('renewed_date', models.DateTimeField(null=True)),
                ('next_renewal_date', models.DateField(null=True)),
                ('renewal_count', models.IntegerField(default=0)),
                ('last_issued_date', models.DateTimeField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='books.Book')),
                ('issued_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_to', to='members.Member')),
                ('last_issued_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_issued_to', to='members.Member')),
            ],
        ),
    ]
